export const midiNotes = [
  { midiId: 12, name: 'C' },
  { midiId: 13, name: 'C#' },
  { midiId: 14, name: 'D' },
  { midiId: 15, name: 'D#' },
  { midiId: 16, name: 'E' },
  { midiId: 17, name: 'F' },
  { midiId: 18, name: 'F#' },
  { midiId: 19, name: 'G' },
  { midiId: 20, name: 'G#' },
  { midiId: 21, name: 'A' },
  { midiId: 22, name: 'A#' },
  { midiId: 23, name: 'B' },
  { midiId: 24, name: 'C' },
  { midiId: 25, name: 'C#' },
  { midiId: 26, name: 'D' },
  { midiId: 27, name: 'D#' },
  { midiId: 28, name: 'E' },
  { midiId: 29, name: 'F' },
  { midiId: 30, name: 'F#' },
  { midiId: 31, name: 'G' },
  { midiId: 32, name: 'G#' },
  { midiId: 33, name: 'A' },
  { midiId: 34, name: 'A#' },
  { midiId: 35, name: 'B' },
  { midiId: 36, name: 'C' },
  { midiId: 37, name: 'C#' },
  { midiId: 38, name: 'D' },
  { midiId: 39, name: 'D#' },
  { midiId: 40, name: 'E' },
  { midiId: 41, name: 'F' },
  { midiId: 42, name: 'F#' },
  { midiId: 43, name: 'G' },
  { midiId: 44, name: 'G#' },
  { midiId: 45, name: 'A' },
  { midiId: 46, name: 'A#' },
  { midiId: 47, name: 'B' },
  { midiId: 48, name: 'C' },
  { midiId: 49, name: 'C#' },
  { midiId: 50, name: 'D' },
  { midiId: 51, name: 'D#' },
  { midiId: 52, name: 'E' },
  { midiId: 53, name: 'F' },
  { midiId: 54, name: 'F#' },
  { midiId: 55, name: 'G' },
  { midiId: 56, name: 'G#' },
  { midiId: 57, name: 'A' },
  { midiId: 58, name: 'A#' },
  { midiId: 59, name: 'B' },
  { midiId: 60, name: 'C' },
  { midiId: 61, name: 'C#' },
  { midiId: 62, name: 'D' },
  { midiId: 63, name: 'D#' },
  { midiId: 64, name: 'E' },
  { midiId: 65, name: 'F' },
  { midiId: 66, name: 'F#' },
  { midiId: 67, name: 'G' },
  { midiId: 68, name: 'G#' },
  { midiId: 69, name: 'A' },
  { midiId: 70, name: 'A#' },
  { midiId: 71, name: 'B' },
  { midiId: 72, name: 'C' },
  { midiId: 73, name: 'C#' },
  { midiId: 74, name: 'D' },
  { midiId: 75, name: 'D#' },
  { midiId: 76, name: 'E' },
  { midiId: 77, name: 'F' },
  { midiId: 78, name: 'F#' },
  { midiId: 79, name: 'G' },
  { midiId: 80, name: 'G#' },
  { midiId: 81, name: 'A' },
  { midiId: 82, name: 'A#' },
  { midiId: 83, name: 'B' },
  { midiId: 84, name: 'C' },
  { midiId: 85, name: 'C#' },
  { midiId: 86, name: 'D' },
  { midiId: 87, name: 'D#' },
  { midiId: 88, name: 'E' },
  { midiId: 89, name: 'F' },
  { midiId: 90, name: 'F#' },
  { midiId: 91, name: 'G' },
  { midiId: 92, name: 'G#' },
  { midiId: 93, name: 'A' },
  { midiId: 94, name: 'A#' },
  { midiId: 95, name: 'B' },
  { midiId: 96, name: 'C' },
  { midiId: 97, name: 'C#' },
  { midiId: 98, name: 'D' },
  { midiId: 99, name: 'D#' },
  { midiId: 100, name: 'E' },
  { midiId: 101, name: 'F' },
  { midiId: 102, name: 'F#' },
  { midiId: 103, name: 'G' },
  { midiId: 104, name: 'G#' },
  { midiId: 105, name: 'A' },
  { midiId: 106, name: 'A#' },
  { midiId: 107, name: 'B' },
  { midiId: 108, name: 'C' },
  { midiId: 109, name: 'C#' },
  { midiId: 110, name: 'D' },
  { midiId: 111, name: 'D#' },
  { midiId: 112, name: 'E' },
  { midiId: 113, name: 'F' },
  { midiId: 114, name: 'F#' },
  { midiId: 115, name: 'G' },
  { midiId: 116, name: 'G#' },
  { midiId: 117, name: 'A' },
  { midiId: 118, name: 'A#' },
  { midiId: 119, name: 'B' },
]

const _nameToNoteMap = midiNotes.reduce(
  (acc, item) => {
    acc[item.name] = item.midiId
    return acc
  },
)

export function nameToMidi (name) {
  return _nameToNoteMap[name]
}

const _noteToNameMap = midiNotes.reduce(
  (acc, item) => {
    acc[item.midiId] = item.name
    return acc
  },
)

export function midiToName (midi) {
  return _noteToNameMap[midi]
}
